<h1>Numpy</h1>

A library for Python, NumPy lets you work with huge, multidimensional matrices and arrays. Along with that, it provides a gamut of high-level functions to perform mathematical operations on these structures.
it was Written in- Python Programming, C
Python NumPy is cross-platform and BSD-licensed.
The term ‘Numpy’ is a portmanteau of the words ‘NUMerical’ and ‘PYthon’.
Numpy is a python library to create homogeneous multidimensional arrays and provide tools for working with these arrays.

Using Numpy, you can perform following operations:

Mathematical and logical operations on arrays.
Fourier transforms and routines for shape manipulation.
Operations related to linear algebra. NumPy has inbuilt functions for linear algebra and random number generation.

<h1>Features of Numpy</h1>
Numpy offers several features, some of the features offered by Numpy are:
<ul>
<li>NumPy stands on CPython, a non-optimizing bytecode interpreter.</li>
<li>Multidimensional arrays.</li>
<li>Functions and operators for these arrays.</li>
<li>Python Alternative to MATLAB.</li>
<li>ndarray- n-dimensional arrays.</li>
<li>Fourier transforms and shapes manipulation.</li>
<li>Linear algebra and random number generation.</li>
    </ul>

 <h1>NumPy, NdArrays and attributes</h1>
 Numpy is a python library to create homogeneous multidimensional arrays and provide tools for working with these arrays.
The elements of numpy array are of the same type. One can create an array in Python using lists or array() function. The advantage of using Numpy array is it scales better and takes less memory when compared to standard Python list or array.

Using Numpy, you can perform following operations:
<ul>
<li>Mathematical and logical operations on arrays.</li>
<li>Fourier transforms and routines for shape manipulation.</li>
</ul>

<h1>Ndarray and Ndarray Attributes</h1>
NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. Here is some most important attribute of the ndarray object:
<h3>ndarray.ndim</h3>: the number of dimensions of the array. In Numpy, the number of dimensions is also the rank of the array.
<h3>ndarray.shape</h3>: A tuple of integers representing the size of an array. For a matrix with n rows and m columns, the shape will be (n,m).
<h3>ndarray.size</h3>: the total number of elements of the array. It is also equal to the product of the elements of shape.
<h3>ndarray.dtype</h3>: It is an object that describes the type of the elements in the array.
<h3>ndarray.data</h3>: It is a buffer that contains the actual elements of the array.

In [1]:
import numpy as np 
np.zeros((2,2))   # Create an array of all zeros

array([[0., 0.],
       [0., 0.]])

In [2]:
np.ones((1,2))

array([[1., 1.]])

In [3]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

<h1>Numpy array from existing data</h1>
This function is useful for converting Python sequence into ndarray.

<h2></>Learn</h2>

In [5]:
# convert list to ndarray
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


<h1>Array Operations</h1>
<h2>Arithmetic Operations</h2>
<ul>
<li>We can perform basic arithmetic operations on any two numpy arrays. Basic operations like addition, subtraction, multiplication and division can be done using both +, -, *, / symbols or add(), subtract(), multiply(), divide() methods. We can also find the square root of each element in numpy array by using sqrt() function.</li><ul>

In [6]:
x= np.array([[1,2],[3,4]], dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)
(x + y)

array([[ 6.,  8.],
       [10., 12.]])

In [7]:
(x - y)

array([[-4., -4.],
       [-4., -4.]])

In [8]:
(x * y)

array([[ 5., 12.],
       [21., 32.]])

In [9]:
(x / y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [10]:
(np.sqrt(x))

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

<h1>Matrix Operations</h1>
<ul><li>n-dimension array can be treated as n-order matrix. We can perform matrix operations on these numpy array matrix such as calculating dot product, transpose of a matrix, etc.</li></ul>

In [11]:
v = np.array([9,10])
w = np.array([11, 12])
# Inner product of vectors; both produce 219
(v.dot(w))
(np.dot(v, w))

219

In [12]:
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [13]:
x = np.array([[1,2],[3,4]])
(np.sum(x))         # Compute sum of all elements; prints "10"
(np.sum(x, axis=0)) # Compute sum of each column; prints "[4 6]"
(np.sum(x, axis=1)) # Compute sum of each row; prints "[3 7]"
(np.min(x, axis=1)) # Compute min of each row'

array([1, 3])

<h1>NumPy Array Indexing and Slicing</h1>

Numpy offers several ways to index into arrays. As mentioned earlier, items in numpy array object follow zero-based index. The three types of indexing methods that are followed in numpy − field access, basic slicing, and advanced indexing.
Here are the 3 topics we will look into in this article:
<ul>
<li>Slicing</li> <li>Integer array indexing</li> <li>Boolean array indexing</li>
</ul>

<h1>Slicing</h1>
<ul><li>Slicing of numpy array is similar to slicing a Python list. Since arrays may be multidimensional, you must specify a slice for each dimension of the array</li>
<li>For one-dimensional array specify single slice</li>
</li></ul>

In [14]:
# Create the following rank 2 array with shape (3, 4)
# [[ 11  12  13  14]
#  [ 25  26  27  28]
#  [ 39 30 31 32]]
a = np.array([[11,12,13,14], [25,26,27,28], [39,30,31,32]])
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[12 13]
#  [26 27]]
b = a[:2, 1:3]
(a[0, 1])   # Prints "12"


12

<h1>Integer array indexing</h1>

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:


In [15]:
a = np.array([[41,42], [43, 44], [45, 46]])
# An example of integer array indexing.
# The returned array will have shape (3,) and
(a[[0, 1, 2], [0, 1, 0]])  # Prints "[41 44 45]"

array([41, 44, 45])

<h1>Boolean array indexing</h1>

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [16]:
a = np.array([[1,2], [3, 4], [5, 6]])

# this returns a numpy array of Booleans of the same
# shape as a, where each slot tells
# whether that element of a is > 2.

(a > 2)      # Prints "[[False False]
# [ True  True]
# [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of a > 2

(a[a > 2])     # Prints "[3 4 5 6]"


array([3, 4, 5, 6])

<h1>Opening and Closing a "File Object"</h1>
<ul><li>Create a file object using the open() function. Along with the file name, specify: 'r' for reading in an existing file (default; can be dropped), 'w' for creating a new file for writing, 'a' for appending new content to an existing file.</li>
<li>Do something with the file object (reading, writing).</li>
<li>Close the file object by calling the .close() method on the file object.</li>
<li>Below, myfile is the file data object we're creating for reading. 'alice.txt' is a pre-existing text file in the same directory as the foo.py script. After the file content is read in, .close() is called on myfile, closing the file object.</li></ul>

In [17]:
myfile = open('alice.txt', 'r')     # Reading. 'r' can be omitted
#read from myfile ...
myfile.close()                      # Closing file

FileNotFoundError: [Errno 2] No such file or directory: 'alice.txt'

<h1>Functions of NumPy Array</h1>

Let’s take a look at all that we can do to an array and what more we can find out about it

<h2>Function: reshape</h2>

The reshape function in numpy allows us to reshape the arrays based on our requirements.

In [18]:
a=np.array([[1,2,3],[4,5,6]])
(a.reshape(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

<h2>Function ndim</h2>

The ndim function returns the number of dimensions of the numpy array.


In [19]:
a=np.array([[1,2,3],[4,5,6]])
(a.ndim) #Number of array dimensions

2

<h2>Function: itemsize</h2>

    The itemsize function returns the length of each element in bytes.

In [20]:
(np.array([[1,2,3],[4,5,6]]).itemsize) #Length of each element in bytes

4

<h2>Function: flags</h2>

The flags function returns the information about the memory layout of the array.


In [21]:
a=np.array([[1,2,3],[4,5,6]])
(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

<h1>Mathematical Functions on Arrays in NumPy</h1>

Let’s now look at some mathematical functions to call on arrays.

<h2>Function: add</h2>

The add function helps to add the elements of different arrays



In [22]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
(np.add(a,b)) #a+b does the same

array([[ 8, 10, 12],
       [14, 16, 18]])

<h2>Function: subtract</h2>

The subtract function is used to subtract elements of one array from the other

In [23]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
(np.subtract(a,b)) #a-b does the same


array([[-6, -6, -6],
       [-6, -6, -6]])

<h2>Function: multiply</h2>

The multiply function is used to multiply the elements of one array with the other.

In [24]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
(np.multiply(a,b)) #a*b does the same


array([[ 7, 16, 27],
       [40, 55, 72]])

<h2>Function: divide</h2>

The divide function helps to divide the elements of one array with the other.

In [25]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
(np.divide(a,b)) #a/b does the same


array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

<h2>Function: sqrt</h2>

The square root function 'sqrt' helps to find the square root of elements in an array.

In [26]:
a=np.array([[1,2,3],[4,5,6]])
(np.sqrt(a)) #Produces a square root of a

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

<h2>Function: sum</h2>
    
The sum function returns the sum of elements of an array.

In [27]:
a=np.array([[1,2],[3,4]])
(np.sum(a)) #Produces a sum of a

10

Function: sum(To find sum of each column)

In [28]:
a=np.array([[1,2],[3,4]])
print(np.sum(a,axis=0)) #Sum of each column


[4 6]


Function: sum(To find sum of each row)

In [29]:
a=np.array([[1,2],[3,4]])
print(np.sum(a,axis=1)) #Sum of each row

[3 7]


<h2>Function: Transpose(To find transpose of a matrix)</h2>

The Transpose function(T) returns the transpose of a matrix.


In [30]:
a=np.array([[1,2],[3,4]])
print(a.T) #Gives the transpose of a matrix


[[1 3]
 [2 4]]


<h1>Treating missing values and infinite in Numpy</h1>
<ul><li>Missing values can be represented using np.nan object, while np.inf represents infinite.</li></ul>
Let us place some in arr2d.

In [31]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
(arr2)

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

<h1>Compute mean, min, max on the ndarray</h1>

The ndarray has the respective methods to compute this for the whole array.

In [32]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
("Mean value is: ", arr2.mean())
("Max value is: ", arr2.max())
("Min value is: ", arr2.min())

('Min value is: ', 1.0)

<h1>Difference between flatten() and ravel()</h1>
<ul><li>There are 2 popular ways to implement flattening.</li>
<li>That is using the flatten() method and the other using the ravel() method.</li>
<li>The difference between ravel and flatten is, the new array created using ravel is actually a reference to the parent array.</li>
<li>So, any changes to the new array will affect the parent as well,
but is memory efficient since it does not create a copy.</li></ul>

In [33]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
(arr2.flatten())

array([1., 2., 3., 4., 3., 4., 5., 6., 5., 6., 7., 8.])

In [34]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
b1 = arr2.flatten()
b1[0] = 100  # changing b1 does not affect arr2
(arr2)

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

<h1>Finding unique items and the counts</h1>
<ul><li>The np.unique method can be used to get the unique items.</li>
<li>If you want the repetition counts of each item, set the return_counts parameter to True.</li></ul>


In [35]:
np.random.seed(100)#get a same random number we need to set a seed.
arr_rand = np.random.randint(0, 10, size=10)
(arr_rand)

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])